# Generated by Django 6.0.6 on 2026-10-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Loksewa General Knowledge Lead Instructor', max_length=200)),
                ('department', models.CharField(choices=[('Loksewa Preparation', 'Loksewa Preparation'), ('School Education', 'School Education (SEE)'), ('College Education', 'College Education (+2)'), ('Academic Mentorship', 'Academic Mentorship'), ('Curriculum & Content', 'Curriculum & Content Development')], default='Loksewa Preparation', max_length=100)),
                ('description', models.TextField(help_text='Detailed overview of responsibilities and expectations.')),
                ('required_skills', models.TextField(help_text='Key skills and competencies (comma-separated or listed).')),
                ('qualification', models.CharField(help_text="e.g. Master's in Public Administration, Bachelor's in Mathematics", max_length=200)),
                ('experience', models.CharField(help_text='e.g. 2+ Years teaching experience, Freshers eligible', max_length=100)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Hybrid / Remote', 'Hybrid / Remote')], default='Full Time', max_length=50)),
                ('location', models.CharField(default='Kathmandu / Online', help_text='e.g. Kathmandu (Putalisadak), Online, Hybrid', max_length=150)),
                ('deadline', models.DateField(help_text='Last date for candidate submissions.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['deadline', '-created_at'],
            },
        ),
    ]
