# Generated by Django 6.0.6 on 2026-10-01 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('EMPTY', 'Empty / No Text'), ('ERROR', 'Extraction Error'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('extracted_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_extraction', to='applications.application')),
            ],
            options={
                'ordering': ['-extracted_at'],
            },
        ),
    ]
