# Generated by Django 6.0.6 on 2026-10-01 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('resume_ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(default=0.0, help_text='Cosine similarity score in range [0.0, 1.0]')),
                ('match_percentage', models.FloatField(default=0.0, help_text='Cosine similarity converted to percentage (0.0% to 100.0%)')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('ERROR', 'Error'), ('INSUFFICIENT_TEXT', 'Insufficient Text'), ('PENDING', 'Pending')], default='PENDING', max_length=30)),
                ('error_message', models.TextField(blank=True, default='')),
                ('matched_keywords_json', models.TextField(blank=True, default='[]')),
                ('job_vector_json', models.TextField(blank=True, default='{}')),
                ('resume_vector_json', models.TextField(blank=True, default='{}')),
                ('screened_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_screening', to='applications.application')),
            ],
            options={
                'verbose_name': 'Resume Screening Result',
                'verbose_name_plural': 'Resume Screening Results',
                'ordering': ['-match_percentage', '-screened_at'],
            },
        ),
    ]
