# Generated by Django 6.0.6 on 2026-10-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_ai', '0002_resumescreening'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumescreening',
            name='experience_detail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resumescreening',
            name='experience_match',
            field=models.CharField(default='Needs Verification', max_length=50),
        ),
        migrations.AddField(
            model_name='resumescreening',
            name='matched_skills_json',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='resumescreening',
            name='missing_skills_json',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='resumescreening',
            name='qualification_detail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resumescreening',
            name='qualification_match',
            field=models.CharField(default='Needs Verification', max_length=50),
        ),
    ]
