# Generated by Django 6.0.6 on 2026-10-01 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('resume_ai', '0003_resumescreening_experience_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_percentage', models.FloatField(default=0.0)),
                ('matched_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('qualification_match', models.CharField(default='Needs Verification', max_length=50)),
                ('experience_match', models.CharField(default='Needs Verification', max_length=50)),
                ('explanation', models.TextField(blank=True, default='')),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_analysis', to='applications.application')),
            ],
            options={
                'verbose_name': 'Resume Analysis',
                'verbose_name_plural': 'Resume Analyses',
                'ordering': ['-match_percentage', '-analyzed_at'],
            },
        ),
    ]
