# Generated by Django 6.0.6 on 2026-10-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_ai', '0004_resumeanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='ml_confidence_tier',
            field=models.CharField(blank=True, default='', help_text="Inference confidence level ('High', 'Moderate', 'Low')", max_length=20),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='ml_model_version',
            field=models.CharField(blank=True, default='', help_text='Model version used for inference', max_length=50),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='ml_predicted_class',
            field=models.CharField(blank=True, default='', help_text="Predicted relevance class ('Relevant' or 'Not Relevant')", max_length=30),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='ml_prediction_status',
            field=models.CharField(default='PENDING', help_text="ML Inference status ('SUCCESS', 'NO_MODEL', 'INSUFFICIENT_TEXT', 'ERROR', 'PENDING')", max_length=30),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='ml_relevance_probability',
            field=models.FloatField(blank=True, help_text='Estimated relevance probability in range [0.0, 1.0]', null=True),
        ),
        migrations.AddField(
            model_name='resumescreening',
            name='ml_confidence_tier',
            field=models.CharField(blank=True, default='', help_text="Inference confidence level ('High', 'Moderate', 'Low')", max_length=20),
        ),
        migrations.AddField(
            model_name='resumescreening',
            name='ml_model_version',
            field=models.CharField(blank=True, default='', help_text='Model version used for inference', max_length=50),
        ),
        migrations.AddField(
            model_name='resumescreening',
            name='ml_predicted_class',
            field=models.CharField(blank=True, default='', help_text="Predicted relevance class ('Relevant' or 'Not Relevant')", max_length=30),
        ),
        migrations.AddField(
            model_name='resumescreening',
            name='ml_prediction_status',
            field=models.CharField(default='PENDING', help_text="ML Inference status ('SUCCESS', 'NO_MODEL', 'INSUFFICIENT_TEXT', 'ERROR', 'PENDING')", max_length=30),
        ),
        migrations.AddField(
            model_name='resumescreening',
            name='ml_relevance_probability',
            field=models.FloatField(blank=True, help_text='Estimated relevance probability in range [0.0, 1.0]', null=True),
        ),
    ]
