# Generated by Django 6.0.6 on 2026-10-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_ai', '0005_resumeanalysis_ml_confidence_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='analysis_status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing')], default='COMPLETED', help_text='Status of batch or single analysis execution', max_length=20),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Reason for failure if analysis_status is FAILED'),
        ),
    ]
